### ISSUE TITLE
request-transformer only last body parameter added when multipart/form-data

### ISSUE THREAD

**Issue by arvileino** [Kong/kong#2981]
### Summary

request-transformer plugin adds only last form parameter (another-form-param) with _config --data "config.add.body=new-form-param:some_value, another-form-param:some_value"_ **when content type is multipart/form-data** Parameter new-form-param or another-form-param is not defined on request.

### Steps To Reproduce

1. Use request-transformer with config:  --data "config.add.body=api_key:jf34rn23lrn2krn2de213ef,jurisdiction_id:test"
2. Send multipart/form-data request. Only jurisdiction_id is added.
3. Swap parameters. Change  request-transformer config to:  --data "config.add.body=jurisdiction_id:test,api_key:jf34rn23lrn2krn2de213ef"
4. Send multipart/form-data request. Only api_key is added.

### Additional Details & Logs

- Kong version (`$ kong version`) 0.11.0
- Operating System Ubuntu 16.04.3 LTS

**Comment by arvileino** [comment]
Problem might be in https://github.com/Kong/lua-multipart/blob/236b8d9f4f4b6424271ed79dba2ae8189e2bdb17/src/multipart.lua#L129

**Comment by bungle** [comment]
This one is possibly fixed with this:
https://github.com/Kong/lua-multipart/pull/14

@arvileino if you have time to try that, please report back your results.

**Comment by arvileino** [comment]
@bungle 
Looks like bug is still there.

Versions:
- Ubuntu 16.04.3 LTS (Xenial Xerus)
- Kong 0.11.2
- multipart 0.5.2-2 - A simple HTTP multipart encoder/decoder for Lua

Setting API:
```
curl -X POST --url http://localhost:8001/apis/ --data 'name=echo' --data 'uris=/echo/' --data 'upstream_url=http://localhost:8020/'
curl -X POST http://localhost:8001/apis/echo/plugins  --data 'name=request-transformer'  --data 'config.add.body=PARAM1:VALUE1'   --data 'config.add.body=PARAM2:VALUE2'
```

Sending data and getting results:

`curl -X "POST" "http://localhost:8010/echo" -F "address_string=TEST ADDRESS" -F "service_code=73da8c74-49e8-e611-8bc2-005056820025" -F "description=TEST FEEDBACK" -F "first_name=FIRST" -F "last_name=LAST"`

```
127.0.0.1 - - [08/Dec/2017 17:09:51] "POST / HTTP/1.1" 200 -
User-Agent: curl/7.47.0
Accept: */*
Host: localhost:8020
X-Forwarded-Host: localhost
X-Forwarded-Port: 8010
Content-Length: 716
X-Forwarded-For: 127.0.0.1
Connection: keep-alive
Content-Type: multipart/form-data; boundary=------------------------1382b689b76bf0a7
X-Real-Ip: 127.0.0.1
X-Forwarded-Proto: http

--------------------------1382b689b76bf0a7
Content-Disposition: form-data; name="address_string"

TEST ADDRESS
--------------------------1382b689b76bf0a7
Content-Disposition: form-data; name="service_code"

73da8c74-49e8-e611-8bc2-005056820025
--------------------------1382b689b76bf0a7
Content-Disposition: form-data; name="description"

TEST FEEDBACK
--------------------------1382b689b76bf0a7
Content-Disposition: form-data; name="first_name"

FIRST
--------------------------1382b689b76bf0a7
Content-Disposition: form-data; name="last_name"

LAST
--------------------------1382b689b76bf0a7
Content-Disposition: form-data; name="PARAM2"

VALUE2
--------------------------1382b689b76bf0a7--
```

PARAM1 is missing.
