### ISSUE TITLE
Some deleted targets reappear after cleaning target history

### ISSUE THREAD

**Issue by JoyZhang66** [Kong/kong#4338]
### Summary
In my design, I add target to upstream when server starts and delete target when server stops. So there are many targets in target history. But sometimes, after adding or deleting a target and target history is cleaning up, some deleted targets will reappear.

Related logs:

2019/02/22 02:11:52 [notice] 32#0: *4016508 [lua] targets.lua:63: clean_history(): [Target DAO] Starting cleanup of target table for upstream cefdf913-8b92-447a-ae20-e359803182af, client: 127.0.0.1, server: kong_admin, request: "DELETE /upstreams/MyUpstream/targets/MyTarget HTTP/1.1", host: "127.0.0.1:8001"

2019/02/22 09:19:42 [notice] 29#0: *10208991 [lua] targets.lua:63: clean_history(): [Target DAO] Starting cleanup of target table for upstream cefdf913-8b92-447a-ae20-e359803182af, client: 127.0.0.1, server: kong_admin, request: "POST /upstreams/MyUpstream/targets HTTP/1.1", host: "127.0.0.1:8001"

### Additional Details & Logs

- Kong version 1.0.2

**Comment by hishamhm** [comment]
This sounds like the issue that was fixed here:
https://github.com/Kong/kong/commit/bbd62e87c640f862b5b53eae4ec082ed41dfcf1b

The commit above was included in Kong 1.1.0rc1, released yesterday. If you are able to give that version a try in your test environment, that would be excellent!

**Comment by JoyZhang66** [comment]
Thanks for your reply. I can only see this issue in my prod environment, I will see if it happens again when 1.1.0 is released.

**Comment by anujjalan** [comment]
We found similar error as we have a similar setup.

We even tried your patch but error remains same.

I think error happens as we are deleting older targets one by one and in order where its last entry is with weight -> 0. So, other kong nodes at the same time started marking this target as one of the valid target as the entry with weight as 100 was not deleted first.

**Comment by locao** [comment]
Thanks for the report, @JoyZhang66 and @anujjalan. For Kong 2.2 there's no target history anymore (#6336), so this will not happen again.

**Comment by zjlooojoe** [comment]
@locao  Hi, We meet the error "no route to host" because using the old target, using kong v1.5.0. It look like is the same problem. I know the bug is fixed after Kong 2.2 by removing target_histories, but I still wonder why target_histories will raise this problem. Could you do me a favor to describe the reason?

**Comment by zjlooojoe** [comment]
In my case, there are a few of workers with the error “no route to host”, and there are some other workers can find the newest target. This is wired because the balancers is global for all workers and Kong always get balancer throuth balancers. In do_target_event, before v2.2 have the check_target_history function which compares old_history in the target_histories and new_history from dB to decide whether create a new balancer. Because we can fix the problem in prd by using do_upstream_event which will create a new balancer without like compare old_history and new_history in do_target_event so that I think there  must be something wrong in handle target_histories/check_target_history, but I can not find out now...
