### ISSUE TITLE
Cannot remove plugin configuration properties

### ISSUE THREAD

**Issue by chris-branch** [Kong/kong#4802]
### Summary

It's currently impossible to delete configuration properties for an existing plugin.  Based on the API documentation, there are two choices for updating the configuration for an existing plugin:

1. PATCH /plugins/{plugin id}
2. PUT /plugins/{plugin id}

However, both methods essentially perform a "merge" operation such that only those properties that are explicitly included in the request body are added/updated.  Any properties that are omitted from the request will retain their existing values from the existing configuration in the database.  This potentially makes sense when using the PATCH method, but is unexpected when using PUT.

In my specific situation, I have a custom plugin that has several configuration properties.  As part of some refactoring work, I want to remove several configuration options that are no longer needed.  Before I can safely remove these from the plugin's schema, I need to update the existing plugin configurations in my database to remove the deprecated properties.  However, I'm not able to do this via the API because both PATCH and PUT will not delete omitted properties.

### Steps To Reproduce

1. Follow the instructions at https://hub.docker.com/_/kong to run kong with postgres locally
2. Create a plugin (I'm using the jwt plugin for this example, but the issue not specific to the jwt plugin):

```
POST http://localhost:8001/plugins
{
    "name": "jwt"
}
```
Response:
```
{
    "created_at": 1563333303,
    "config": {
        "secret_is_base64": false,
        "key_claim_name": "iss",
        "cookie_names": [],
        "maximum_expiration": 0,
        "claims_to_verify": null,
        "anonymous": null,
        "run_on_preflight": true,
        "uri_param_names": [
            "jwt"
        ]
    },
    "id": "16e8dba7-bf2b-484d-b43e-e936435fea64",
    "service": null,
    "name": "jwt",
    "protocols": [
        "http",
        "https"
    ],
    "enabled": true,
    "run_on": "first",
    "consumer": null,
    "route": null,
    "tags": null
}
```

3. Use the PUT verb to attempt to remove the "run_on_preflight" property:

```
PUT http://localhost:8001/plugins/16e8dba7-bf2b-484d-b43e-e936435fea64
{
    "created_at": 1563333303,
    "config": {
        "secret_is_base64": false,
        "key_claim_name": "iss",
        "cookie_names": [],
        "maximum_expiration": 0,
        "claims_to_verify": null,
        "anonymous": null,
        "uri_param_names": [
            "jwt"
        ]
    },
    "id": "16e8dba7-bf2b-484d-b43e-e936435fea64",
    "service": null,
    "name": "jwt",
    "protocols": [
        "http",
        "https"
    ],
    "enabled": true,
    "run_on": "first",
    "consumer": null,
    "route": null,
    "tags": null
}
```
Response: (Note that "run_on_preflight" is still present)
```
{
    "created_at": 1563333303,
    "config": {
        "secret_is_base64": false,
        "key_claim_name": "iss",
        "cookie_names": [],
        "maximum_expiration": 0,
        "claims_to_verify": null,
        "anonymous": null,
        "run_on_preflight": true,
        "uri_param_names": [
            "jwt"
        ]
    },
    "id": "16e8dba7-bf2b-484d-b43e-e936435fea64",
    "service": null,
    "name": "jwt",
    "protocols": [
        "http",
        "https"
    ],
    "enabled": true,
    "run_on": "first",
    "consumer": null,
    "route": null,
    "tags": null
}
```

I'm not certain whether the current behavior of PUT is working as intended.  Typically, from a RESTful perspective, PUT (or POST) would completely replace the target resource and not perform merging with existing data.  However, I understand how that might result in unintended changes in the case of plugins.  If it's considered too risky for PUT to perform a wholesale replace, perhaps the implementation for PUT could be modified to perform a merge for the top-level elements (created_at, id, name, etc.) but perform a replace for the "config" element.  Another potential solution is if the PATCH verb could be extended to support JSON Merge Patch (RFC 7396) where deletes can be requested explicitly by setting specific properties to null (and use the Content Type header to choose between the existing merge behavior vs. the RFC 7396 for handling null values).

Currently, once a configuration property has been added to the database, it cannot be removed via the API (without completely deleting and recreating the plugin).

### Additional Details & Logs

- Kong version (`$ kong version`) - 1.2.1

**Comment by ccjinghang** [comment]
Hello.
I had the same problem, but I found a solution.
You can do the following:
PUT http://localhost:8001/plugins/16e8dba7-bf2b-484d-b43e-e936435fea64
{
    "created_at": 1563333303,
    "config": {
        "secret_is_base64": false,
        "key_claim_name": "iss",
        "cookie_names": [],
        "maximum_expiration": 0,
        "claims_to_verify": null,
        **"run_on_preflight": null,**
        "anonymous": null,
        "uri_param_names": [
            "jwt"
        ]
    },
    "id": "16e8dba7-bf2b-484d-b43e-e936435fea64",
    "service": null,
    "name": "jwt",
    "protocols": [
        "http",
        "https"
    ],
    "enabled": true,
    "run_on": "first",
    "consumer": null,
    "route": null,
    "tags": null
}
I know that doesn't solve the problem at the source.This is kong's bug.Hopefully the next release will solve this problem

**Comment by charlie-retzler** [comment]
@ccjinghang While the workaround you provided does set the value to null it doesn't really solve the problem reported. We are forced to leave legacy fields in our plugin's schema or to recreate the plugin configuration entirely due to how terraform interacts with kong.

Do we know if it is intentional that the PUT merges the values passed with the existing values? Typically PUT replaces the entire object rather than merging. PATCH is the typical mechanism for updating select fields in a object.

**Comment by ccjinghang** [comment]
@charlie-retzler Yes, this approach cannot solve the problem at its source.It prevents you from deleting plugin and recreating them.Hopefully the next release will solve this problem.

**Comment by bungle** [comment]
I feel it is this line that is causing the problem:
https://github.com/Kong/kong/blob/master/kong/db/dao/plugins.lua#L112

**Comment by bungle** [comment]
There is now a PR that we might still get cherry picked for `1.3.0` release, if not, then to a release after that.

**Comment by bungle** [comment]
Closing this as the fix was merged.

**Comment by yongzhang** [comment]
I still have this issue with my custom plugin:

```
   "config": {
     "rules": {
-      "must_have_all": null,
       "must_have_any": [
         "x-roles~tag"
       ],
-      "must_not_have_all": null,
-      "must_not_have_any": null
     }
   },
```
I use deck to sync changes, after rules updated, I can still see the changes.
Kong version: 2.8.1
