### ISSUE TITLE
Not able to Overwrite client_body_buffer_size directive value 

### ISSUE THREAD

**Issue by jambagigirish** [Kong/kong#5444]
Cant overwrite client_body_buffer_size through nginx directive

### Steps To Reproduce

1. Docker file with env variable 
	KONG_NGINX_PROXY_CLIENT_BODY_BUFFER_SIZE="32k"

2.Build Image and bring up the kong container with database(postgres)

### Additional Details & Logs

- Kong version (1.4 centos )
-
- Kong debug-level startup logs
Error: /usr/local/share/lua/5.1/kong/cmd/start.lua:37: nginx configuration is invalid (exit code 1):
nginx: [emerg] "client_body_buffer_size" directive is duplicate in /usr/local/kong/nginx-kong.conf:84
nginx: configuration file /usr/local/kong/nginx.conf test failed

- Kong error logs 
Error: /usr/local/share/lua/5.1/kong/cmd/start.lua:37: nginx configuration is invalid (exit code 1):
nginx: [emerg] "client_body_buffer_size" directive is duplicate in /usr/local/kong/nginx-kong.conf:84
nginx: configuration file /usr/local/kong/nginx.conf test failed

- Operating system-

**Comment by bungle** [comment]
This is already fixed on `next` thus closing this, see:
https://github.com/Kong/kong/pull/5390

**Comment by dobl1** [comment]
Hello I'm running `kong:1.5.1-alpine` (latest 1.x version)
I still have the issue is it normal ?

**Comment by dobl1** [comment]
@jambagigirish Did you solve your issue ?
Not having to migrate to v2.X of kong ?

**Comment by dobl1** [comment]
Update :

Weirdly, and unaccrodingly to the docs.
Using KONG_CLIENT_MAX_BODY_SIZE and KONG_CLIENT_BODY_BUFFER_SIZE instead of KONG_NGINX_HTTP_CLIENT_MAX_BODY_SIZE and KONG_NGINX_PROXY_CLIENT_BODY_BUFFER_SIZE work well.

-> https://github.com/Kong/kong/issues/5828

**Comment by jambagigirish** [comment]
After migrating to 2.0 and with #5390  it fixed issues for me
