### ISSUE TITLE
Get consumer by username is not found when username is a UUID

### ISSUE THREAD

**Issue by cuongnc5** [Kong/kong#7182]
### Summary
- Kong version ('Latest`)
- A concise summary of the bug.

### Steps To Reproduce

1. Create consumer with username (length = 37 charaters): 40af65f4-2a40-4ab2-bb9d-bf1ee39ecab3
2. Get consumer by username  http://localhost:8001/consumers/40af65f4-2a40-4ab2-bb9d-bf1ee39ecab3
Now: Result always "message": "Not found"
Expected: consumer info with username 40af65f4-2a40-4ab2-bb9d-bf1ee39ecab3

**Comment by gszr** [comment]
Hi @cuongnc5,

Welcome to the Kong community.

Thanks for reporting, I can reproduce on my end.

**Comment by jeremyjpj0916** [comment]
Interesting, using a uuid as the consumer username must be tricking Kong under the hood 😄 . Because the URI of the admin api endpoint expects a username or uuid, but since passing a uuid(which you set as a username) its doing a uuid lookup and not finding that uuid as a primary id in db when it would need to fall back on looking that id up by username field if their admin APIs maintain the way they are designed.

**Comment by gszr** [comment]
> Interesting, using a uuid as the consumer username must be tricking Kong under the hood 😄 . Because the URI of the admin api endpoint expects a username or uuid, but since passing a uuid(which you set as a username) its doing a uuid lookup and not finding that uuid as a primary id in db when it would need to fall back on looking that id up by username field if their admin APIs maintain the way they are designed, probably decision tree now just parses the inbound URI field to see if its in a UUID format to see if its a primary id lookup vs username.

This is precisely what happened @jeremyjpj0916 😃  We are working on a fix.

**Comment by cuongnc5** [comment]
> Thật thú vị, việc sử dụng uuid làm tên người dùng của người tiêu dùng hẳn đang lừa Kong 😄. Bởi vì URI của điểm cuối api quản trị viên yêu cầu một tên người dùng hoặc uuid, nhưng vì chuyển một uuid (mà bạn đặt làm tên người dùng), nó thực hiện tra cứu uuid và không tìm thấy uuid đó làm id chính trong db khi nó cần phải quay lại khi tìm kiếm id đó theo trường tên người dùng nếu các API quản trị của họ duy trì cách chúng được thiết kế, có thể cây quyết định bây giờ chỉ cần phân tích cú pháp trường URI đến để xem trường đó có ở định dạng UUID hay không để xem liệu đó có phải là tra cứu id chính so với tên người dùng hay không.

**Comment by cuongnc5** [comment]
> > Interesting, using a uuid as the consumer username must be tricking Kong under the hood 😄 . Because the URI of the admin api endpoint expects a username or uuid, but since passing a uuid(which you set as a username) its doing a uuid lookup and not finding that uuid as a primary id in db when it would need to fall back on looking that id up by username field if their admin APIs maintain the way they are designed, probably decision tree now just parses the inbound URI field to see if its in a UUID format to see if its a primary id lookup vs username.
> 
> This is precisely what happened @jeremyjpj0916 😃 We are working on a fix.

I'm sorry, I mistakenly pressed the close button and I used uuid as the username. I'm not trying to trick Kong : EASY
Because before integrating kong into the system, we had a user table - it linked to many other tables by userId. So I used userId as username on Kong. Maybe I was wrong. I should reconsider using username. :D

**Comment by bungle** [comment]
I am not sure if that is a bug or by design. If the url is uuid we look by consumer id. Otherwise we look by endpoint key. I think that is pretty good as is, perhaps better documentation could be done. Please remember that when you do:
```bash
http put :8001/consumers/40af65f4-2a40-4ab2-bb9d-bf1ee39ecab3 username=jack
```

It will use `40af65f4-2a40-4ab2-bb9d-bf1ee39ecab3` as an id.

**Comment by bungle** [comment]
Alternative would be to add support for all unique fields, e.g.:
```
http get :8001/consumers/username:40af65f4-2a40-4ab2-bb9d-bf1ee39ecab3
```

or something like that. We already also do support this:
```
http get :8001/consumers?custom_id=<custom-id>
```

**Comment by DiySane** [comment]
@gszr I am interested in the issue. Would love to have bit of an insight.

**Comment by StarlightIbuki** [comment]
Dear contributor,
We're closing this issue as there hasn't been any update to it for a long time. If the issue is still relevant in the latest version, please feel free to reopen it. We're more than happy to revisit it again. Your contribution is greatly appreciated!
Please have a look at [our pledge to the community](https://github.com/Kong/kong/blob/master/COMMUNITY_PLEDGE.md) for more information.
Sincerely,
Kong Gateway Team

**Comment by Silviu-Nicola** [comment]
Somebody should fix this ...

**Comment by brucetony** [comment]
This is very much still an issue and would like to see this reopened and revisited

**Comment by kikito** [comment]
> a uuid as the consumer username must be tricking Kong under the hood

[jeremyjpj0916](https://github.com/jeremyjpj0916) is exactly right, that is what is happening under the hood. It's not that the username is longer than 36 characters, but that the query value looks like a UUID.

Unfortunately fixing this issue is not something we can do at this time, for several reasons: the logic which handles the username/uuid has diverged between Enterprise and Opensource, and in addition the part of the code that would have to be modified affects all entities on the gateway, which would make it very easy to introduce undesired side effects and we'd rather not risk breaking other things with the change. There's a couple workarounds that can be used.

## Workarounds

No workaround is needed for ids that don't look like UUIDs.

First workaround consists on adding an extra character to the ids so that they don't look like UUIDs any more.
* For the example that opened the ticket, adding a `u` to the username should be enough: `u40af65f4-2a40-4ab2-bb9d-bf1ee39ecab3` is not a valid UUID any more so it will get matched as a name.

Second workaround consist on using the `custom_id` property instead of `username` when a uuid-looking identifier is needed. For the example that opened the ticket, two changes would be needed:
* Instead of creating a consumer with `username=40af65f4-2a40-4ab2-bb9d-bf1ee39ecab3`, create it with `custom_id=40af65f4-2a40-4ab2-bb9d-bf1ee39ecab3`
* Instead of `http://localhost:8001/consumers/40af65f4-2a40-4ab2-bb9d-bf1ee39ecab3` , use this other query instead: `http://localhost:8001/consumers/?custom_id=40af65f4-2a40-4ab2-bb9d-bf1ee39ecab3`

Note: It's possible to create a consumer with the same `username` and `custom_id`. On the example above the consumer can still have `40af65f4-2a40-4ab2-bb9d-bf1ee39ecab3` as their username. It's just that the `custom_id` is the field that should be used for querying

As we are not going to fix this issue any time soon, I'm closing this as a "won't fix". Hopefully the workarounds proposed will help alleviating the inconvenience.
